# Generated by Django 6.0.6 on 2026-09-01 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_remove_cliente_domicilio_cliente_barrio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(db_index=True, max_length=30, unique=True)),
                ('nombre_whatsapp', models.CharField(blank=True, max_length=200)),
                ('ultimo_mensaje_en', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ultimo_mensaje_entrante_en', models.DateTimeField(blank=True, null=True)),
                ('no_leidos', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_whatsapp', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Conversación de WhatsApp',
                'verbose_name_plural': 'Conversaciones de WhatsApp',
                'ordering': ['-ultimo_mensaje_en', '-actualizada_en'],
            },
        ),
        migrations.CreateModel(
            name='MensajeWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_message_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('direccion', models.CharField(choices=[('entrante', 'Entrante'), ('saliente', 'Saliente')], db_index=True, max_length=10)),
                ('tipo', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Documento'), ('sticker', 'Sticker'), ('location', 'Ubicación'), ('contacts', 'Contacto'), ('reaction', 'Reacción'), ('unknown', 'Desconocido')], default='text', max_length=20)),
                ('texto', models.TextField(blank=True)),
                ('media_id', models.CharField(blank=True, max_length=255)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('fecha_mensaje', models.DateTimeField(db_index=True)),
                ('estado', models.CharField(choices=[('received', 'Recibido'), ('pending', 'Pendiente'), ('sent', 'Enviado'), ('delivered', 'Entregado'), ('read', 'Leído'), ('failed', 'Fallido')], db_index=True, default='received', max_length=20)),
                ('leido_en_fortex', models.BooleanField(default=False)),
                ('fecha_leido_en_fortex', models.DateTimeField(blank=True, null=True)),
                ('error_codigo', models.CharField(blank=True, max_length=100)),
                ('error_detalle', models.TextField(blank=True)),
                ('payload_original', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='mensajeria.conversacionwhatsapp')),
            ],
            options={
                'verbose_name': 'Mensaje de WhatsApp',
                'verbose_name_plural': 'Mensajes de WhatsApp',
                'ordering': ['fecha_mensaje', 'id'],
                'indexes': [models.Index(fields=['conversacion', 'fecha_mensaje'], name='msg_wa_conv_fecha_idx'), models.Index(fields=['estado', 'fecha_mensaje'], name='msg_wa_estado_fecha_idx')],
            },
        ),
    ]
