# Generated by Django 6.0.6 on 2026-09-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajewhatsapp',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mensajewhatsapp',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mensajewhatsapp',
            name='ubicacion_direccion',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='mensajewhatsapp',
            name='ubicacion_nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
