# Generated by Django 6.0.6 on 2026-07-01 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polizas', '0003_poliza_tipo_seguro_alter_poliza_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('numero_cuota', models.PositiveIntegerField(default=1)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('forma_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta', 'Tarjeta'), ('CBU', 'Débito CBU')], default='Efectivo', max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polizas.poliza')),
            ],
        ),
    ]
