# Generated by Django 6.0.6 on 2026-07-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='emitido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recibo',
            name='numero_recibo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
