# Generated by Django 6.0.6 on 2026-08-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recibos', '0002_recibo_emitido_recibo_numero_recibo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='cantidad_cuotas',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
