# Generated by Django 6.0.6 on 2026-07-02 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_remove_cliente_domicilio_cliente_barrio_and_more'),
        ('polizas', '0003_poliza_tipo_seguro_alter_poliza_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de pago')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cuota', models.PositiveIntegerField(default=1)),
                ('forma_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Débito', 'Débito'), ('Tarjeta', 'Tarjeta')], default='Efectivo', max_length=30)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado')], default='Pagado', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polizas.poliza')),
            ],
        ),
    ]
