# Generated by Django 6.0.6 on 2026-08-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobro',
            name='cantidad_cuotas',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
