# Generated by Django 6.0.6 on 2026-08-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0002_cobro_cantidad_cuotas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobro',
            name='plus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
