# Generated by Django 6.0.6 on 2026-08-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0003_cobro_plus'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobro',
            name='comision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
