# Generated by Django 6.0.6 on 2026-08-17 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0004_cobro_comision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cobro',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cobro',
            name='anulado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cobros_anulados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cobro',
            name='echa_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cobro',
            name='motivo_anulacion',
            field=models.TextField(blank=True),
        ),
    ]
