# Generated by Django 6.0.6 on 2026-08-17 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0005_cobro_anulado_cobro_anulado_por_cobro_echa_anulacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cobro',
            old_name='echa_anulacion',
            new_name='fecha_anulacion',
        ),
    ]
