# Generated by Django 6.0.6 on 2026-08-18 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0007_cobro_fecha_registro_cobro_registrado_por'),
        ('principal', '0006_alter_cierrecaja_fecha_turnocaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobro',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='principal.turnocaja'),
        ),
    ]
