# Generated by Django 6.0.6 on 2026-07-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='anio',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='uso',
            field=models.CharField(choices=[('Particular', 'Particular'), ('Taxi', 'Taxi'), ('Remis', 'Remis'), ('Moto', 'Moto'), ('Camioneta', 'Camioneta'), ('Camión', 'Camión'), ('Furgón', 'Furgón'), ('Acoplado', 'Acoplado')], default='Particular', max_length=30),
        ),
    ]
