# Generated by Django 6.0.6 on 2026-08-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_vehiculo_anio_vehiculo_observaciones_vehiculo_uso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='uso',
            field=models.CharField(choices=[('Particular', 'Particular'), ('Comercial', 'Comercial'), ('Taxi', 'Taxi'), ('Remis', 'Remis'), ('Moto', 'Moto'), ('Camioneta', 'Camioneta'), ('Camión', 'Camión'), ('Furgón', 'Furgón'), ('Acoplado', 'Acoplado')], default='Particular', max_length=30),
        ),
    ]
