# Generated by Django 6.0.6 on 2026-08-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_alter_vehiculo_uso'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('Moto', 'Moto'), ('Auto', 'Auto'), ('Camioneta', 'Camioneta'), ('Furgón', 'Furgón'), ('Camión', 'Camión'), ('Acoplado', 'Acoplado'), ('Tráiler', 'Tráiler')], default='Auto', max_length=30),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='uso',
            field=models.CharField(choices=[('Particular', 'Particular'), ('Comercial', 'Comercial'), ('Taxi', 'Taxi'), ('Remis', 'Remis'), ('Moto', 'Moto'), ('Camioneta', 'Camioneta'), ('Camión', 'Camión'), ('Furgón', 'Furgón'), ('Acoplado', 'Acoplado'), ('Tráiler', 'Tráiler')], default='Particular', max_length=30),
        ),
    ]
