# Generated by Django 6.0.6 on 2026-08-08 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_vehiculo_tipo_alter_vehiculo_uso'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marca de vehículo',
                'verbose_name_plural': 'Marcas de vehículos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ModeloVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Moto', 'Moto'), ('Auto', 'Auto'), ('Camioneta', 'Camioneta'), ('Furgón', 'Furgón'), ('Camión', 'Camión'), ('Acoplado', 'Acoplado'), ('Tráiler', 'Tráiler')], default='Auto', max_length=30)),
                ('activa', models.BooleanField(default=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='vehiculos.marcavehiculo')),
            ],
            options={
                'verbose_name': 'Modelo de vehículo',
                'verbose_name_plural': 'Modelos de vehículos',
                'ordering': ['marca__nombre', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('marca', 'nombre', 'tipo'), name='modelo_vehiculo_unico')],
            },
        ),
    ]
