# Generated by Django 6.0.6 on 2026-08-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0005_marcavehiculo_modelovehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelovehiculo',
            name='anio_desde',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelovehiculo',
            name='anio_hasta',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
