# Generated by Django 6.0.6 on 2026-08-10 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0006_modelovehiculo_anio_desde_modelovehiculo_anio_hasta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloAnio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anios', to='vehiculos.modelovehiculo')),
            ],
            options={
                'ordering': ['anio'],
                'constraints': [models.UniqueConstraint(fields=('modelo', 'anio'), name='unique_modelo_anio')],
            },
        ),
    ]
