# Generated by Django 6.0.6 on 2026-07-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_email_remove_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Prospecto', 'Prospecto')], default='Activo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_alternativo',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono alternativo'),
        ),
    ]
