# Generated by Django 6.0.6 on 2026-07-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_email_cliente_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='domicilio',
        ),
        migrations.AddField(
            model_name='cliente',
            name='barrio',
            field=models.CharField(blank=True, max_length=100, verbose_name='Barrio'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='calle',
            field=models.CharField(blank=True, max_length=150, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código postal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='departamento',
            field=models.CharField(blank=True, max_length=20, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='piso',
            field=models.CharField(blank=True, max_length=20, verbose_name='Piso'),
        ),
    ]
