# Generated by Django 6.0.6 on 2026-07-30 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_remove_cliente_domicilio_cliente_barrio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cliente', 'Datos del cliente'), ('riesgo', 'Riesgo'), ('poliza', 'Póliza'), ('cobro', 'Cobro'), ('recibo', 'Recibo'), ('whatsapp', 'WhatsApp'), ('endoso', 'Endoso'), ('aseguradora', 'Cambio de aseguradora'), ('otro', 'Otro')], max_length=20)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='clientes.cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento del cliente',
                'verbose_name_plural': 'Movimientos de clientes',
                'ordering': ['-fecha'],
            },
        ),
    ]
