# Generated by Django 6.0.6 on 2026-08-15 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_aseguradora'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('total_cobrado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_neto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tarjeta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transferencia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_hora_cierre', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
