# Generated by Django 6.0.6 on 2026-08-18 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_alter_cierrecaja_fecha_turnocaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastocaja',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='principal.turnocaja'),
        ),
    ]
