# Generated by Django 6.0.6 on 2026-08-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_gastocaja_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnocaja',
            name='saldo_neto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='turnocaja',
            name='total_cobrado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='turnocaja',
            name='total_gastos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
