# Generated by Django 6.0.6 on 2026-08-25 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecaja',
            name='cbu',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cierres', to='principal.turnocaja'),
        ),
    ]
