# Generated by Django 6.0.6 on 2026-08-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_cierrecaja_cbu_cierrecaja_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecaja',
            name='debito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
