# Generated by Django 6.0.6 on 2026-07-01 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_remove_cliente_email_remove_cliente_telefono_and_more'),
        ('vehiculos', '0002_vehiculo_anio_vehiculo_observaciones_vehiculo_uso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compania', models.CharField(max_length=100, verbose_name='Compañía')),
                ('numero_poliza', models.CharField(blank=True, max_length=50, verbose_name='Número de póliza')),
                ('fecha_alta', models.DateField(verbose_name='Fecha de alta')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('numero_cuota', models.PositiveIntegerField(default=1, verbose_name='Número de cuota')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Vigente', 'Vigente'), ('Vencida', 'Vencida'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculo')),
            ],
        ),
    ]
