# Generated by Django 6.0.6 on 2026-07-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='cantidad_cuotas',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad de cuotas'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='periodicidad',
            field=models.CharField(choices=[('Mensual', 'Mensual'), ('Bimestral', 'Bimestral'), ('Trimestral', 'Trimestral'), ('Cuatrimestral', 'Cuatrimestral'), ('Semestral', 'Semestral'), ('Anual', 'Anual')], default='Mensual', max_length=20),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
    ]
