# Generated by Django 6.0.6 on 2026-07-01 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0002_poliza_cantidad_cuotas_poliza_periodicidad_and_more'),
        ('vehiculos', '0002_vehiculo_anio_vehiculo_observaciones_vehiculo_uso'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='tipo_seguro',
            field=models.CharField(choices=[('Automotor', 'Automotor'), ('Moto', 'Moto'), ('Caución', 'Caución'), ('Accidentes Personales', 'Accidentes Personales'), ('Agro', 'Agro'), ('Hogar', 'Hogar'), ('Comercio', 'Comercio'), ('Otro', 'Otro')], default='Automotor', max_length=50),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehiculos.vehiculo'),
        ),
    ]
