# Generated by Django 6.0.6 on 2026-07-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0003_poliza_tipo_seguro_alter_poliza_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='fecha_fin_vigencia',
            field=models.DateField(blank=True, null=True, verbose_name='Fin de vigencia'),
        ),
    ]
