# Generated by Django 6.0.6 on 2026-08-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0004_poliza_fecha_fin_vigencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='estado',
            field=models.CharField(choices=[('Al día', 'Al día'), ('Pendiente', 'Pendiente'), ('Morosa', 'Morosa')], default='Pendiente', max_length=20),
        ),
    ]
