# Generated by Django 6.0.6 on 2026-08-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0005_alter_poliza_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='numero_cuota',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de cuota'),
        ),
    ]
