# Generated by Django 6.0.6 on 2026-08-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0006_alter_poliza_numero_cuota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='estado',
            field=models.CharField(choices=[('Al día', 'Al día'), ('Pendiente', 'Pendiente'), ('Morosa', 'Morosa'), ('Vencida', 'Vencida')], default='Pendiente', max_length=20),
        ),
    ]
