# Generated by Django 6.0.6 on 2026-08-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0007_alter_poliza_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='porcentaje_comision',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje de comisión'),
        ),
    ]
