# Generated by Django 6.0.6 on 2026-08-18 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0008_poliza_porcentaje_comision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='anulada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polizas_anuladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poliza',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='motivo_anulacion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='estado',
            field=models.CharField(choices=[('Al día', 'Al día'), ('Pendiente', 'Pendiente'), ('Morosa', 'Morosa'), ('Vencida', 'Vencida'), ('Anulada', 'Anulada')], default='Pendiente', max_length=20),
        ),
    ]
