# Generated by Django 6.0.6 on 2026-09-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0009_poliza_anulada_por_poliza_fecha_anulacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='importe_cuota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Importe de cuota'),
        ),
    ]
