# Generated by Django 6.0.6 on 2026-09-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0010_poliza_importe_cuota'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='cobertura',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Cobertura'),
        ),
    ]
