# Generated by Django 6.0.6 on 2026-09-23 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mensajeria', '0003_suscripcionpush'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteraccionNexa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('interno', 'FORTEX interno'), ('whatsapp', 'WhatsFORTEX')], db_index=True, max_length=20)),
                ('consulta', models.TextField()),
                ('respuesta', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('respondida', 'Respondida por NEXA'), ('derivada', 'Derivada a operador'), ('escalada', 'Escalada a Victoria'), ('pendiente', 'Pendiente')], db_index=True, default='pendiente', max_length=20)),
                ('requiere_revision_humana', models.BooleanField(default=False)),
                ('motivo_escalamiento', models.TextField(blank=True)),
                ('datos_consultados', models.JSONField(blank=True, default=dict)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('respondida_en', models.DateTimeField(blank=True, null=True)),
                ('conversacion_whatsapp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacciones_nexa', to='mensajeria.conversacionwhatsapp')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacciones_nexa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interacción NEXA',
                'verbose_name_plural': 'Interacciones NEXA',
                'ordering': ['-creada_en'],
            },
        ),
    ]
