# Generated by Django 6.0.6 on 2026-09-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaccionnexa',
            name='identidad_verificada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interaccionnexa',
            name='motivo_bloqueo_privacidad',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interaccionnexa',
            name='respuesta_bloqueada_privacidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interaccionnexa',
            name='tipo_interlocutor',
            field=models.CharField(choices=[('cliente', 'Cliente verificado'), ('cliente_no_verificado', 'Cliente sin verificar'), ('tercero', 'Tercero'), ('desconocido', 'Desconocido')], db_index=True, default='desconocido', max_length=30),
        ),
    ]
